In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Diabetes.csv")

In [4]:
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
df.describe()

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

In [8]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [9]:
df.shape

(768, 9)

In [10]:
#get dependent and independent variable

In [11]:
y=df["diabetes"]

In [12]:
y.shape

(768,)

In [13]:
X=df.drop('diabetes',axis=1)

In [14]:
X

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0              6      148         72       35        0  33.6  0.627   50
1              1       85         66       29        0  26.6  0.351   31
2              8      183         64        0        0  23.3  0.672   32
3              1       89         66       23       94  28.1  0.167   21
4              0      137         40       35      168  43.1  2.288   33
..           ...      ...        ...      ...      ...   ...    ...  ...
763           10      101         76       48      180  32.9  0.171   63
764            2      122         70       27        0  36.8  0.340   27
765            5      121         72       23      112  26.2  0.245   30
766            1      126         60        0        0  30.1  0.349   47
767            1       93         70       31        0  30.4  0.315   23

[768 rows x 8 columns]

In [15]:
#X Variable Standardlized

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
mm=MinMaxScaler()

In [19]:
X=mm.fit_transform(X)

In [20]:
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=53)

In [24]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((537, 8), (231, 8), (537,), (231,))

In [25]:
from sklearn.linear_model import LogisticRegression

In [27]:
lr=LogisticRegression()

In [29]:
lr.fit(X_train,y_train)

LogisticRegression()

In [30]:
y_pred=lr.predict(X_test)

In [31]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [32]:
y_pred.shape

(231,)

In [33]:
#get probability of each predicted class

In [34]:
lr.predict_proba(X_test)

array([[0.855904  , 0.144096  ],
       [0.79448878, 0.20551122],
       [0.74928997, 0.25071003],
       [0.83193659, 0.16806341],
       [0.94912445, 0.05087555],
       [0.66366847, 0.33633153],
       [0.5404501 , 0.4595499 ],
       [0.2352207 , 0.7647793 ],
       [0.6002316 , 0.3997684 ],
       [0.73520415, 0.26479585],
       [0.67645484, 0.32354516],
       [0.6204695 , 0.3795305 ],
       [0.16581725, 0.83418275],
       [0.54201247, 0.45798753],
       [0.37191266, 0.62808734],
       [0.78341418, 0.21658582],
       [0.84821444, 0.15178556],
       [0.79751085, 0.20248915],
       [0.62175593, 0.37824407],
       [0.59746167, 0.40253833],
       [0.71735084, 0.28264916],
       [0.40289873, 0.59710127],
       [0.58438533, 0.41561467],
       [0.82336716, 0.17663284],
       [0.92539932, 0.07460068],
       [0.55135632, 0.44864368],
       [0.65206355, 0.34793645],
       [0.74518587, 0.25481413],
       [0.61484231, 0.38515769],
       [0.5751318 , 0.4248682 ],
       [0.

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [39]:
print(confusion_matrix(y_test,y_pred))

[[126  17]
 [ 40  48]]


In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.88      0.82       143
           1       0.74      0.55      0.63        88

    accuracy                           0.75       231
   macro avg       0.75      0.71      0.72       231
weighted avg       0.75      0.75      0.74       231



In [73]:
X_new=df.sample(1)

In [74]:
X_new

pregnancies  glucose  diastolic  triceps  insulin   bmi   dpf  age  \
447            0       95         80       45       92  36.5  0.33   26   

     diabetes  
447         0

In [75]:
X_new.shape

(1, 9)

In [76]:
X_new=X_new.drop('diabetes',axis=1)

In [77]:
X_new=mm.fit_transform(X_new)

In [78]:
X_new

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
lr.predict(X_new)

array([0], dtype=int64)